# Generated by Django 3.2.4 on 2021-06-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='https://via.placeholder.com/250x250/', null=True, upload_to='shop_main/static/images/', verbose_name='Изображение'),
        ),
    ]
