# Generated by Django 3.2.4 on 2021-06-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
    ]
