# Generated by Django 3.2.4 on 2021-06-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main', '0004_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='shop_main/static/images/default_image.png', null=True, upload_to='shop_main/static/images/', verbose_name='Изображение'),
        ),
    ]
