# Generated by Django 3.2.4 on 2021-06-25 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main', '0007_alter_cart_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='count',
            new_name='total_count',
        ),
    ]
