# Generated by Django 3.2.4 on 2021-06-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main', '0004_alter_cart_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cost_per_item',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
