# Generated by Django 3.2.4 on 2021-08-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main', '0005_cart_cost_per_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.CharField(choices=[('SuccessTransaction', 'Успешная транзакция'), ('UnsuccessfulTransaction', 'Неудачная транзакция')], default='UnsuccessfulTransaction', max_length=25, verbose_name='Статус транзакции')),
            ],
        ),
    ]
